# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "ab61baa9a51936f91b3172926778db6f"
name = "notify-me"
handle = "notify-me-40"
application_url = "https://april-mass-custom-easter.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
include_config_on_deploy = true

[webhooks]
api_version = "2025-04"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://april-mass-custom-easter.trycloudflare.com/auth/callback",
  "https://april-mass-custom-easter.trycloudflare.com/auth/shopify/callback",
  "https://april-mass-custom-easter.trycloudflare.com/api/auth/callback"
]

[pos]
embedded = false
